app:
  secret: secret
  refresh: refresh
  cors: http://localhost:8080
  first_user:
    username: "user@example.com"
    password: "userPassword"

spring:
  output.ansi.enabled: ALWAYS
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/proddb
      database: proddb
