server.port: 3000
app:
  secret: secret
  refresh: refresh
  cors: http://localhost:3000
  first_user:
    username: "user@example.com"
    password: "userPassword"

spring:
  output.ansi.enabled: ALWAYS
  mongodb.embedded.version: 4.0.2
  data:
    mongodb:
      database: mongo-db
springdoc.api-docs.path: /docs

---
spring:
  config.activate.on-profile: mongo
  data:
    mongodb:
#      uri: mongodb://admin:password@localhost:27017/mongo-db?authSource=admin
      host: localhost
      username: admin
      password: password
      authentication-database: admin
